name: dart_code_viewer2
description: A package to view Dart Code in your Flutter application. This
  package is null safety version of dart-code-viewer
version: 1.0.0
homepage: https://github.com/verkit/dart_code_viewer2/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  string_scanner: ^1.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter: null
